linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G404 # Use of weak random number generator

output:
  print-issued-lines: true
  print-linter-name: true
