linters:
  enable:
    - gofmt
    - govet
    - unused
    - unparam

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
        - unparam

linters-settings:
  gofmt:
    simplify: true

output:
  print-issued-lines: true
  print-linter-name: true
